// Mock Room Data
import { NextApiRequest, NextApiResponse } from "next";


export const mockRooms = [
    {
        id: 1,
        roomType: "Superior Garden View",
        price: 3000,
        promotionPrice: 2500,
        guest: 2,
        bedType: "Double Bed",
        roomSize: 32,
        imageUrl: "https://picsum.photos/seed/s9OoJHPN/3274/1293",
    },
    {
        id: 2,
        roomType: "Deluxe",
        price: 3000,
        promotionPrice: 2500,
        guest: 2,
        bedType: "Double Bed",
        roomSize: 32,
        imageUrl: "https://picsum.photos/seed/SM4qUVI/2117/143",
    },
    {
        id: 3,
        roomType: "Superior",
        price: 3000,
        promotionPrice: 2500,
        guest: 2,
        bedType: "Double Bed",
        roomSize: 32,
        imageUrl: "https://picsum.photos/seed/z6cLBkCYlQ/3522/3031",
    },
    {
        id: 4,
       roomType: "Premier Sea View",
        price: 3000,
        promotionPrice: 2500,
        guest: 2,
        bedType: "Double Bed",
        roomSize: 32,
        imageUrl: "https://picsum.photos/seed/vexhlNdX/3581/2350",
    },
    {
        id: 5,
       roomType: "Supreme",
        price: 3000,
        promotionPrice: 2500,
        guest: 2,
        bedType: "Double Bed",
        roomSize: 32,
        imageUrl: "https://picsum.photos/seed/qcN9BL/2606/2619",
    },
    {
        id: 6,
       roomType: "Suite",
        price: 3000,
        promotionPrice: 2500,
        guest: 2,
        bedType: "Double Bed",
        roomSize: 32,
        imageUrl: "https://picsum.photos/seed/s9OoJHPN/3274/1293"
    },
     {
        id: 7,
        roomType: "Superior Garden View",
        price: 3000,
        promotionPrice: 2500,
        guest: 2,
        bedType: "Double Bed",
        roomSize: 32,
        imageUrl: "https://picsum.photos/seed/s9OoJHPN/3274/1293",
    },
    {
        id: 8,
        roomType: "Deluxe",
        price: 3000,
        promotionPrice: 2500,
        guest: 2,
        bedType: "Double Bed",
        roomSize: 32,
        imageUrl: "https://picsum.photos/seed/SM4qUVI/2117/143",
    },
    {
        id: 9,
        roomType: "Superior",
        price: 3000,
        promotionPrice: 2500,
        guest: 2,
        bedType: "Double Bed",
        roomSize: 32,
        imageUrl: "https://picsum.photos/seed/z6cLBkCYlQ/3522/3031",
    },
    {
        id: 10,
       roomType: "Premier Sea View",
        price: 3000,
        promotionPrice: 2500,
        guest: 2,
        bedType: "Double Bed",
        roomSize: 32,
        imageUrl: "https://picsum.photos/seed/vexhlNdX/3581/2350",
    },
    {
        id: 11,
       roomType: "Supreme",
        price: 3000,
        promotionPrice: 2500,
        guest: 2,
        bedType: "Double Bed",
        roomSize: 32,
        imageUrl: "https://picsum.photos/seed/qcN9BL/2606/2619",
    },
    {
        id: 12,
       roomType: "Suite",
        price: 3000,
        promotionPrice: 2500,
        guest: 2,
        bedType: "Double Bed",
        roomSize: 32,
        imageUrl: "https://picsum.photos/seed/s9OoJHPN/3274/1293"
    },
  ];

  export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json(mockRooms);
}